In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sqlalchemy import create_engine

In [22]:


df= pd.read_csv('Healthcare_EDA_Dataset.csv')
df.head()

,PatientID,FirstName,LastName,Age,Gender,BloodGroup,HeightCM,WeightKG,BMI,City,...,Alcohol,SystolicBP,DiastolicBP,HeartRate,Temperature,Glucose,Cholesterol,TreatmentCost,PaymentStatus,Outcome
0,P000001,Ananya,Sharma,32,Male,A+,154.0,57.0,24.0,Chennai,...,Occasionally,93,95,80,101.5,249.0,259,118303.26,Pending,Improved
1,P000002,Arjun,Yadav,1,Female,A-,188.0,60.0,17.0,Chennai,...,No,167,76,60,101.6,NaN,151,43455.10,Pending,Recovered
2,P000003,Riya,Yadav,74,Male,NaN,152.0,48.0,20.8,Pune,...,No,110,83,100,98.0,138.0,299,197051.69,Insurance,Recovered
3,P000004,Priya,Kapoor,21,Male,B-,169.0,88.0,30.8,Hyderabad,...,Yes,117,96,95,98.0,197.0,221,137080.54,Insurance,Referred
4,P000005,Diya,Patel,32,Female,AB-,187.0,111.0,31.7,Bengaluru,...,Yes,104,69,75,102.0,178.0,272,179615.67,Paid,Referred

In [23]:
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 30 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         10200 non-null  object
 1   FirstName         10200 non-null  object
 2   LastName          10200 non-null  object
 3   Age               10200 non-null  int64
 4   Gender            9691 non-null   object
 5   BloodGroup        9692 non-null   object
 6   HeightCM          9693 non-null   float64
 7   WeightKG          9696 non-null   float64
 8   BMI               10200 non-null  float64
 9   City              9693 non-null   object
 10  State             10200 non-null  object
 11  Department        10200 non-null  object
 12  Diagnosis         9689 non-null   object
 13  AdmissionType     10200 non-null  object
 14  AdmissionDate     10200 non-null  object
 15  DischargeDate     10200 non-null  object
 16  LengthOfStay      10200 non-null  int64
 17  DoctorExperience  10200 non-null  int64
 18  Insurance         9690 non-null   object
 19  Smoking           10200 non-null  object
 20  Alcohol           10200 non-null  object
 21  SystolicBP        10200 non-null  int64
 22  DiastolicBP       10200 non-null  int64
 23  HeartRate         10200 non-null  int64
 24  Temperature       10200 non-null  float64
 25  Glucose           9690 non-null   float64
 26  Cholesterol       10200 non-null  int64
 27  TreatmentCost     9688 non-null   float64
 28  PaymentStatus     10200 non-null  object
 29  Outcome           10200 non-null  object
dtypes: float64(6), int64(7), object(17)
memory usage: 2.3+ MB

In [24]:
df.isnull().sum()

PatientID             0
FirstName             0
LastName              0
Age                   0
Gender              509
BloodGroup          508
HeightCM            507
WeightKG            504
BMI                   0
City                507
State                 0
Department            0
Diagnosis           511
AdmissionType         0
AdmissionDate         0
DischargeDate         0
LengthOfStay          0
DoctorExperience      0
Insurance           510
Smoking               0
Alcohol               0
SystolicBP            0
DiastolicBP           0
HeartRate             0
Temperature           0
Glucose             510
Cholesterol           0
TreatmentCost       512
PaymentStatus         0
Outcome               0
dtype: int64

In [25]:
df.shape

(10200, 30)

In [26]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['BloodGroup'].fillna(df['BloodGroup'].mode()[0], inplace=True)
df['HeightCM'].fillna(df['HeightCM'].median() , inplace=True)
df['WeightKG'].fillna(df['WeightKG'].median() , inplace=True)
df['City'].fillna("Unknown", inplace=True)
df['Diagnosis'].fillna("Not Recorded", inplace=True)
df['Insurance'].fillna("Unknown", inplace=True)
df['TreatmentCost'].fillna(df['TreatmentCost'].median() , inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 30 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         10200 non-null  object
 1   FirstName         10200 non-null  object
 2   LastName          10200 non-null  object
 3   Age               10200 non-null  int64
 4   Gender            10200 non-null  object
 5   BloodGroup        10200 non-null  object
 6   HeightCM          10200 non-null  float64
 7   WeightKG          10200 non-null  float64
 8   BMI               10200 non-null  float64
 9   City              10200 non-null  object
 10  State             10200 non-null  object
 11  Department        10200 non-null  object
 12  Diagnosis         10200 non-null  object
 13  AdmissionType     10200 non-null  object
 14  AdmissionDate     10200 non-null  object
 15  DischargeDate     10200 non-null  object
 16  LengthOfStay      10200 non-null  int64
 17  DoctorExperience  10200 non-null  int64
 18  Insurance         10200 non-null  object
 19  Smoking           10200 non-null  object
 20  Alcohol           10200 non-null  object
 21  SystolicBP        10200 non-null  int64
 22  DiastolicBP       10200 non-null  int64
 23  HeartRate         10200 non-null  int64
 24  Temperature       10200 non-null  float64
 25  Glucose           9690 non-null   float64
 26  Cholesterol       10200 non-null  int64
 27  TreatmentCost     10200 non-null  float64
 28  PaymentStatus     10200 non-null  object
 29  Outcome           10200 non-null  object
dtypes: float64(6), int64(7), object(17)
memory usage: 2.3+ MB

In [28]:
df.isnull().sum()

PatientID             0
FirstName             0
LastName              0
Age                   0
Gender                0
BloodGroup            0
HeightCM              0
WeightKG              0
BMI                   0
City                  0
State                 0
Department            0
Diagnosis             0
AdmissionType         0
AdmissionDate         0
DischargeDate         0
LengthOfStay          0
DoctorExperience      0
Insurance             0
Smoking               0
Alcohol               0
SystolicBP            0
DiastolicBP           0
HeartRate             0
Temperature           0
Glucose             510
Cholesterol           0
TreatmentCost         0
PaymentStatus         0
Outcome               0
dtype: int64

In [29]:
df["Grp Age"] = df["Age"].apply(lambda x : "Child" if x < 18 else "Adult" if x < 60 else "Senior")

In [30]:
df["Grp Age"]

0         Adult
1         Child
2        Senior
3         Adult
4         Adult
          ...
10195    Senior
10196     Child
10197     Adult
10198    Senior
10199    Senior
Name: Grp Age, Length: 10200, dtype: object

In [31]:
df.to_csv('Cleaned_Healthcare_EDA_Dataset.csv', index=False)

In [32]:
df.duplicated().sum()

np.int64(197)

In [33]:
df.drop_duplicates()

,PatientID,FirstName,LastName,Age,Gender,BloodGroup,HeightCM,WeightKG,BMI,City,...,SystolicBP,DiastolicBP,HeartRate,Temperature,Glucose,Cholesterol,TreatmentCost,PaymentStatus,Outcome,Grp Age
0,P000001,Ananya,Sharma,32,Male,A+,154.0,57.0,24.0,Chennai,...,93,95,80,101.5,249.0,259,118303.26,Pending,Improved,Adult
1,P000002,Arjun,Yadav,1,Female,A-,188.0,60.0,17.0,Chennai,...,167,76,60,101.6,NaN,151,43455.10,Pending,Recovered,Child
2,P000003,Riya,Yadav,74,Male,B+,152.0,48.0,20.8,Pune,...,110,83,100,98.0,138.0,299,197051.69,Insurance,Recovered,Senior
3,P000004,Priya,Kapoor,21,Male,B-,169.0,88.0,30.8,Hyderabad,...,117,96,95,98.0,197.0,221,137080.54,Insurance,Referred,Adult
4,P000005,Diya,Patel,32,Female,AB-,187.0,111.0,31.7,Bengaluru,...,104,69,75,102.0,178.0,272,179615.67,Paid,Referred,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9998,P009999,Arjun,Khan,34,Female,O+,160.0,46.0,18.0,Jaipur,...,135,79,120,99.9,72.0,306,127434.86,Pending,Improved,Adult
9999,P010000,Meera,Kapoor,32,Male,B+,184.0,94.0,27.8,Pune,...,146,72,58,100.0,74.0,277,79199.90,Pending,Recovered,Adult
10039,P001959,Diya,Singh,84,Other,A-,165.0,49.0,24.6,Lucknow,...,139,99,104,97.1,250.0,180,35737.09,Pending,Recovered,Senior
10076,P001322,Aditya,Khan,10,Other,A-,166.0,49.0,17.8,Unknown,...,176,107,120,97.5,119.0,255,157662.37,Pending,Referred,Child
10129,P007601,Diya,Das,32,Other,A-,165.0,60.0,22.0,Bengaluru,...,125,105,100,102.7,210.0,256,11170.12,Insurance,Improved,Adult

In [34]:
df[df.duplicated(subset=['PatientID'], keep=False)]
df = df.drop_duplicates(subset=['PatientID'], keep='first')

In [35]:
df.head

<bound method NDFrame.head of      PatientID FirstName LastName  Age  Gender BloodGroup  HeightCM  WeightKG  \
0      P000001    Ananya   Sharma   32    Male         A+     154.0      57.0
1      P000002     Arjun    Yadav    1  Female         A-     188.0      60.0
2      P000003      Riya    Yadav   74    Male         B+     152.0      48.0
3      P000004     Priya   Kapoor   21    Male         B-     169.0      88.0
4      P000005      Diya    Patel   32  Female        AB-     187.0     111.0
...        ...       ...      ...  ...     ...        ...       ...       ...
9995   P009996      Riya    Joshi   57    Male         B-     178.0      88.0
9996   P009997      Neha      Das   10   Other         O-     144.0      60.0
9997   P009998      Aman     Khan   23   Other         B+     155.0      88.0
9998   P009999     Arjun     Khan   34  Female         O+     160.0      46.0
9999   P010000     Meera   Kapoor   32    Male         B+     184.0      94.0

       BMI       City  ... SystolicBP DiastolicBP HeartRate Temperature  \
0     24.0    Chennai  ...         93          95        80       101.5
1     17.0    Chennai  ...        167          76        60       101.6
2     20.8       Pune  ...        110          83       100        98.0
3     30.8  Hyderabad  ...        117          96        95        98.0
4     31.7  Bengaluru  ...        104          69        75       102.0
...    ...        ...  ...        ...         ...       ...         ...
9995  27.8  Ahmedabad  ...        159          84        55       100.8
9996  28.9     Mumbai  ...        153          73       109       100.3
9997  36.6    Lucknow  ...        172          78        80        97.5
9998  18.0     Jaipur  ...        135          79       120        99.9
9999  27.8       Pune  ...        146          72        58       100.0

     Glucose Cholesterol  TreatmentCost  PaymentStatus          Outcome  \
0      249.0         259      118303.26        Pending         Improved
1        NaN         151       43455.10        Pending        Recovered
2      138.0         299      197051.69      Insurance        Recovered
3      197.0         221      137080.54      Insurance         Referred
4      178.0         272      179615.67           Paid         Referred
...      ...         ...            ...            ...              ...
9995   187.0         291       91197.21           Paid        Recovered
9996   254.0         265      133498.87        Pending         Improved
9997     NaN         198      121253.84           Paid  Under Treatment
9998    72.0         306      127434.86        Pending         Improved
9999    74.0         277       79199.90        Pending        Recovered

     Grp Age
0      Adult
1      Child
2     Senior
3      Adult
4      Adult
...      ...
9995   Adult
9996   Child
9997   Adult
9998   Adult
9999   Adult

[10000 rows x 31 columns]>

In [36]:
df.to_sql('healthcare_data', con=engine, if_exists='replace', index=False)

10000